config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index,:edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :members
  has_many :users, through: :members
  validates :name, presence: true
  def show_last_message
    if (last_message = messages.last).present?
      last_message.body? ? last_message.body : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  validates :body, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :members
  has_many :groups, through: :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice:'グループが作成されました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice:'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end
  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json{@new_messages = @messages.where("id > ?",params[:message][:id])}
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html {redirect_to group_messages_path(@group)}
        format.json
      end
      flash[:notice] = 'メッセージが送信されました'
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)',"%#{params[:keyword]}%").where.not(name: current_user.name)
    respond_to do |format|
      format.html
      format.json
    end
  end
  def edit
  end
  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    .chat-group-form__errors
      %h2
        = "#{@group.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - @group.errors.full_messages.each do |message|
            %li
              = message
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix

    .chat-group-form__field--left
      = f.label :chat_group_チャットメンバーを追加, "チャットメンバーを追加", class: "chat-group-form__label"
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        = f.text_field :members, value:"",type: "text",placeholder:"追加したいユーザー名を入力してください",class:"chat-group-form__input",id:"user-search-field"
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      .chat-group-user.clearfix
        %input{name: "group[user_ids][]", type:"hidden",value:"#{current_user.id}"}
        %p.chat-group-user__name
        = current_user.name
      .chat-group-users

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'form'

app/views/groups/index.html.haml
= render '/messages/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form'

app/views/layouts/_head_bar.html.haml
.head_bar
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    =render 'layouts/head_bar'
    = yield

app/views/messages/_chat.html.haml
.chat
  .chat__group
    .chat-contents
      .name
        = @group.name
      .members
        Members:
        - @group.users.each do |user|
          = user.name
    = link_to "EDIT",edit_group_path(@group),class:"edit_button"

  %hr
  .chat__space
    = render @messages
  .chat__form
    = form_for [@group,@message] do |f|
      = f.text_field :body,class: 'text', placeholder: 'type a message'
      = f.submit class: 'button',value: "SEND"
      = f.label :image do
        = fa_icon "image",class: 'send-icon'
        = f.file_field :image, class: 'hidden'

app/views/messages/_message.haml
.message(data-message-id='#{message.id}')
  %span.user_name
    = message.user.name
  %span.created_at
    = message.created_at.to_s(:datetime)
  .body
    = message.body
  .message_image
    = image_tag message.image if message.image.present?

app/views/messages/_side_bar.html.haml
.side_bar
  .side_bar__name
    = current_user.name
    %span.icon_bar
      = link_to new_group_path do
        = fa_icon "edit",class: 'icon'
      = link_to edit_user_path(current_user) do
        = fa_icon "cog",class: 'icon'
  .side_bar__group
    - current_user.groups.each do |group|
      = link_to group_messages_path(group), class:"link" do
        .group_name
          = group.name
        .last_message
          = group.show_last_message

app/views/messages/index.html.haml
= render 'side_bar'
= render 'chat'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'